import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import PageFadeWrapper from "@/components/PageFadeWrapper";
import { ThemeProvider } from "@/components/ThemeProvider";
import { TravelProvider } from "@/context/travelContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <TravelProvider>
            <Header />
            <PageFadeWrapper>{children}</PageFadeWrapper>
          </TravelProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
